name: Sanity check

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  checks:
    name: Various checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup testing dependencies
        uses: ./.github/actions/test-setup
        with:
          start-dev-env: false

      - name: Run checks
        run: make check

      - name: Run unit tests
        run: make unit-test

  integration-tests:
    strategy:
      fail-fast: false
      matrix:
        # Due to Scylla issue #16349 it is expected that restore-schema
        # jobs with the following config will fail (4 jobs total):
        # - scylla-version: scylla:5.2.X,               raft-enabled: true
        # - scylla-version: scylla-enterprise:2024.1.X, raft-enabled: true
        scylla-version: [ 'scylla:5.4.1', 'scylla-enterprise:2024.1.0-rc4' ]
        ip-family: [ IPV4, IPV6 ]
        dst-raft-enabled: [ false ]
        src-raft-enabled: [ true, false ]
        test-name: [ "TestRestoreSchemaSmokeIntegration", "TestRestoreSchemaVersionedIntegration", "TestRestoreFullViewSSTableSchemaIntegration", "TestRestoreFullIntegration"]
    uses: ./.github/workflows/integration-tests.yaml
    with:
      scylla-version: ${{ matrix.scylla-version }}
      ip-family: ${{ matrix.ip-family }}
      dst-raft-enabled: ${{ matrix.dst-raft-enabled }}
      src-raft-enabled: ${{ matrix.src-raft-enabled }}
      test-name: ${{ matrix.test-name }}