run-name: Integration tests

on:
  workflow_call:
    inputs:
      scylla-version:
        required: false
        type: string
      ip-family:
        required: false
        type: string
      dst-raft-enabled:
        required: false
        type: string
      src-raft-enabled:
        required: false
        type: string
      test-name:
        required: false
        type: string

jobs:
  restore-schema:
    name: Test restore schema
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Setup testing dependencies
        uses: ./.github/actions/test-setup
        with:
          scylla-version: ${{ inputs.scylla-version }}
          ip-family: ${{ inputs.ip-family }}
          dst-raft-enabled: ${{ inputs.dst-raft-enabled }}
          src-raft-enabled: ${{ inputs.src-raft-enabled }}

      - name: Run tests
        run: make pkg-integration-test IP_FAMILY=${{ inputs.ip-family }} PKG=./pkg/service/restore RUN='${{ inputs.test-name }}'

      - name: Enable raft
        run: make -C testing enable-raft

      - name: Validate raft
        run: make pkg-integration-test IP_FAMILY=${{ inputs.ip-family }} PKG=./pkg/service/restore RUN='"TestValidateSpecialRestoreSchemaIntegration"'
